# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 44449ed0db3a5639b41dd3d1dc5bf4f940ef11ceca301cc4f73a1fefbe3e4b2c4fd8d4421b5ffb6088f08713e354aebf8b58b922e8a9d47f3a627d72503bde4e

test:
  secret_key_base: 60e893b42d336d81928f099bdfb238d6c853fc87d556a36e2b781cb60615239fe520cf2a165c39f5acfe788be02a95700cc72ad15e97a4ebbce6a78999c3fc5a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
